"""initial_schema

Revision ID: 32a5ea1e8e79
Revises: 
Create Date: 2025-12-22 14:55:05.893444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32a5ea1e8e79'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('key_id', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key_id')
    )
    op.create_index('idx_api_key_active', 'api_keys', ['is_active'], unique=False)
    op.create_index('idx_api_key_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_table('feature_drift',
    sa.Column('feature_name', sa.String(), nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('reference_start_date', sa.Date(), nullable=True),
    sa.Column('reference_end_date', sa.Date(), nullable=True),
    sa.Column('current_start_date', sa.Date(), nullable=True),
    sa.Column('current_end_date', sa.Date(), nullable=True),
    sa.Column('ks_statistic', sa.Float(), nullable=True),
    sa.Column('psi_value', sa.Float(), nullable=True),
    sa.Column('drift_detected', sa.Boolean(), nullable=True),
    sa.Column('drift_severity', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('feature_name', 'analysis_date')
    )
    op.create_index('idx_drift_date', 'feature_drift', ['analysis_date'], unique=False)
    op.create_index('idx_drift_feature', 'feature_drift', ['feature_name'], unique=False)
    op.create_table('ml_training_data',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('target_direction', sa.Boolean(), nullable=True),
    sa.Column('target_return', sa.Float(), nullable=True),
    sa.Column('split_type', sa.String(), nullable=True),
    sa.Column('fold_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ticker', 'as_of_date')
    )
    op.create_index('idx_ml_train_split', 'ml_training_data', ['split_type'], unique=False)
    op.create_index('idx_ml_train_ticker', 'ml_training_data', ['ticker'], unique=False)
    op.create_table('model_registry',
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('artifact_path', sa.String(), nullable=True),
    sa.Column('feature_names', sa.JSON(), nullable=True),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('training_metrics', sa.JSON(), nullable=True),
    sa.Column('validation_metrics', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('promoted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_index('idx_registry_name_version', 'model_registry', ['model_name', 'model_version'], unique=False)
    op.create_index('idx_registry_status', 'model_registry', ['status'], unique=False)
    op.create_index('idx_registry_ticker', 'model_registry', ['ticker'], unique=False)
    op.create_table('news_sentiment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_news_published', 'news_sentiment', ['published_at'], unique=False)
    op.create_index('idx_news_sentiment', 'news_sentiment', ['sentiment_label'], unique=False)
    op.create_index('idx_news_ticker', 'news_sentiment', ['ticker'], unique=False)
    op.create_table('sec_financial_statements',
    sa.Column('adsh', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('coreg', sa.String(), nullable=False),
    sa.Column('ddate', sa.Date(), nullable=False),
    sa.Column('qtrs', sa.Integer(), nullable=False),
    sa.Column('uom', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('footnote', sa.String(), nullable=True),
    sa.Column('data_year', sa.Integer(), nullable=True),
    sa.Column('data_quarter', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('adsh', 'tag', 'ddate', 'qtrs', 'coreg')
    )
    op.create_index('idx_sec_fs_adsh', 'sec_financial_statements', ['adsh'], unique=False)
    op.create_index('idx_sec_fs_ddate', 'sec_financial_statements', ['ddate'], unique=False)
    op.create_index('idx_sec_fs_tag', 'sec_financial_statements', ['tag'], unique=False)
    op.create_table('sec_submissions',
    sa.Column('adsh', sa.String(), nullable=False),
    sa.Column('cik', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sic', sa.BigInteger(), nullable=True),
    sa.Column('countryba', sa.String(), nullable=True),
    sa.Column('stprba', sa.String(), nullable=True),
    sa.Column('cityba', sa.String(), nullable=True),
    sa.Column('zipba', sa.String(), nullable=True),
    sa.Column('bas1', sa.String(), nullable=True),
    sa.Column('bas2', sa.String(), nullable=True),
    sa.Column('baph', sa.String(), nullable=True),
    sa.Column('countryma', sa.String(), nullable=True),
    sa.Column('stprma', sa.String(), nullable=True),
    sa.Column('cityma', sa.String(), nullable=True),
    sa.Column('zipma', sa.String(), nullable=True),
    sa.Column('mas1', sa.String(), nullable=True),
    sa.Column('mas2', sa.String(), nullable=True),
    sa.Column('countryinc', sa.String(), nullable=True),
    sa.Column('stprinc', sa.String(), nullable=True),
    sa.Column('ein', sa.BigInteger(), nullable=True),
    sa.Column('former', sa.String(), nullable=True),
    sa.Column('changed', sa.String(), nullable=True),
    sa.Column('accession', sa.String(), nullable=True),
    sa.Column('form', sa.String(), nullable=True),
    sa.Column('period', sa.Date(), nullable=True),
    sa.Column('fy', sa.Integer(), nullable=True),
    sa.Column('fp', sa.String(), nullable=True),
    sa.Column('filed', sa.Date(), nullable=True),
    sa.Column('accepted', sa.DateTime(), nullable=True),
    sa.Column('preaccession', sa.String(), nullable=True),
    sa.Column('instance', sa.String(), nullable=True),
    sa.Column('nciks', sa.Integer(), nullable=True),
    sa.Column('aciks', sa.String(), nullable=True),
    sa.Column('data_year', sa.Integer(), nullable=True),
    sa.Column('data_quarter', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('adsh')
    )
    op.create_index('idx_sec_sub_cik', 'sec_submissions', ['cik'], unique=False)
    op.create_index('idx_sec_sub_filed', 'sec_submissions', ['filed'], unique=False)
    op.create_index('idx_sec_sub_form', 'sec_submissions', ['form'], unique=False)
    op.create_index('idx_sec_sub_period', 'sec_submissions', ['period'], unique=False)
    op.drop_index(op.f('idx_sec_filings_cik'), table_name='sec_filings')
    op.drop_index(op.f('idx_sec_filings_date'), table_name='sec_filings')
    op.drop_index(op.f('idx_sec_filings_form'), table_name='sec_filings')
    op.drop_table('sec_filings')
    op.drop_index(op.f('idx_feat_imp_date'), table_name='feature_importance')
    op.drop_index(op.f('idx_feat_imp_model'), table_name='feature_importance')
    op.drop_table('feature_importance')
    op.drop_index(op.f('idx_ftd_date'), table_name='sec_fails_to_deliver')
    op.drop_index(op.f('idx_ftd_symbol'), table_name='sec_fails_to_deliver')
    op.drop_table('sec_fails_to_deliver')
    op.add_column('data_refresh_log', sa.Column('refresh_id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('data_refresh_log', sa.Column('data_source', sa.String(), nullable=False))
    op.add_column('data_refresh_log', sa.Column('refresh_start', sa.DateTime(), nullable=False))
    op.add_column('data_refresh_log', sa.Column('refresh_end', sa.DateTime(), nullable=True))
    op.alter_column('data_refresh_log', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_refresh_time'), table_name='data_refresh_log')
    op.drop_index(op.f('idx_refresh_source'), table_name='data_refresh_log')
    op.create_index('idx_refresh_source', 'data_refresh_log', ['data_source'], unique=False)
    op.create_index('idx_refresh_status', 'data_refresh_log', ['status'], unique=False)
    op.drop_column('data_refresh_log', 'id')
    op.drop_column('data_refresh_log', 'refresh_type')
    op.drop_column('data_refresh_log', 'start_time')
    op.drop_column('data_refresh_log', 'source')
    op.drop_column('data_refresh_log', 'end_time')
    op.add_column('data_retention_policy', sa.Column('archive_to_parquet', sa.Boolean(), nullable=True))
    op.add_column('data_retention_policy', sa.Column('partition_column', sa.String(), nullable=True))
    op.add_column('data_retention_policy', sa.Column('description', sa.String(), nullable=True))
    op.add_column('derived_features', sa.Column('rsi_macd_interaction', sa.Float(), nullable=True))
    op.add_column('derived_features', sa.Column('volume_price_divergence', sa.Float(), nullable=True))
    op.add_column('derived_features', sa.Column('momentum_volatility_ratio', sa.Float(), nullable=True))
    op.add_column('derived_features', sa.Column('volatility_regime', sa.String(), nullable=True))
    op.add_column('derived_features', sa.Column('trend_regime', sa.String(), nullable=True))
    op.add_column('derived_features', sa.Column('volume_regime', sa.String(), nullable=True))
    op.add_column('derived_features', sa.Column('price_zscore', sa.Float(), nullable=True))
    op.add_column('derived_features', sa.Column('sp500_correlation_30d', sa.Float(), nullable=True))
    op.add_column('derived_features', sa.Column('sector_relative_strength', sa.Float(), nullable=True))
    op.add_column('derived_features', sa.Column('market_beta', sa.Float(), nullable=True))
    op.add_column('derived_features', sa.Column('day_of_week', sa.Integer(), nullable=True))
    op.add_column('derived_features', sa.Column('week_of_month', sa.Integer(), nullable=True))
    op.add_column('derived_features', sa.Column('month', sa.Integer(), nullable=True))
    op.add_column('derived_features', sa.Column('quarter', sa.Integer(), nullable=True))
    op.add_column('derived_features', sa.Column('high_low_range', sa.Float(), nullable=True))
    op.add_column('derived_features', sa.Column('close_position_in_range', sa.Float(), nullable=True))
    op.add_column('derived_features', sa.Column('gap_percentage', sa.Float(), nullable=True))
    op.drop_column('derived_features', 'vs_sector_return')
    op.drop_column('derived_features', 'vs_spy_return')
    op.drop_column('derived_features', 'regime')
    op.drop_column('derived_features', 'beta_60d')
    op.drop_column('derived_features', 'term_spread_level')
    op.drop_column('derived_features', 'regime_score')
    op.drop_column('derived_features', 'vix_level')
    op.add_column('ml_predictions', sa.Column('model_version', sa.String(), nullable=False))
    op.add_column('ml_predictions', sa.Column('predicted_probability', sa.Float(), nullable=True))
    op.add_column('ml_predictions', sa.Column('xgboost_prob', sa.Float(), nullable=True))
    op.add_column('ml_predictions', sa.Column('lightgbm_prob', sa.Float(), nullable=True))
    op.add_column('ml_predictions', sa.Column('lstm_prob', sa.Float(), nullable=True))
    op.add_column('ml_predictions', sa.Column('ensemble_prob', sa.Float(), nullable=True))
    op.add_column('ml_predictions', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('ml_predictions', sa.Column('top_features', sa.JSON(), nullable=True))
    op.alter_column('ml_predictions', 'predicted_direction',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using='predicted_direction::boolean')
    op.drop_index(op.f('idx_pred_date'), table_name='ml_predictions')
    op.drop_index(op.f('idx_pred_model'), table_name='ml_predictions')
    op.drop_index(op.f('idx_pred_ticker'), table_name='ml_predictions')
    op.create_index('idx_ml_pred_date', 'ml_predictions', ['prediction_date'], unique=False)
    op.create_index('idx_ml_pred_target', 'ml_predictions', ['target_date'], unique=False)
    op.create_index('idx_ml_pred_ticker', 'ml_predictions', ['ticker'], unique=False)
    op.create_index('idx_ml_pred_ticker_date', 'ml_predictions', ['ticker', 'prediction_date'], unique=False)
    op.drop_column('ml_predictions', 'horizon_days')
    op.drop_column('ml_predictions', 'feature_version')
    op.drop_column('ml_predictions', 'predicted_return')
    op.drop_column('ml_predictions', 'confidence')
    op.drop_column('ml_predictions', 'model_name')
    op.add_column('model_performance', sa.Column('model_version', sa.String(), nullable=False))
    op.add_column('model_performance', sa.Column('ticker', sa.String(), nullable=False))
    op.add_column('model_performance', sa.Column('accuracy', sa.Float(), nullable=True))
    op.add_column('model_performance', sa.Column('precision', sa.Float(), nullable=True))
    op.add_column('model_performance', sa.Column('recall', sa.Float(), nullable=True))
    op.add_column('model_performance', sa.Column('f1_score', sa.Float(), nullable=True))
    op.add_column('model_performance', sa.Column('auc_roc', sa.Float(), nullable=True))
    op.add_column('model_performance', sa.Column('log_loss', sa.Float(), nullable=True))
    op.add_column('model_performance', sa.Column('brier_score', sa.Float(), nullable=True))
    op.add_column('model_performance', sa.Column('sharpe_ratio', sa.Float(), nullable=True))
    op.add_column('model_performance', sa.Column('total_predictions', sa.Integer(), nullable=True))
    op.add_column('model_performance', sa.Column('correct_predictions', sa.Integer(), nullable=True))
    op.add_column('model_performance', sa.Column('evaluation_period_days', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_perf_model'), table_name='model_performance')
    op.create_index('idx_perf_model', 'model_performance', ['model_version'], unique=False)
    op.drop_column('model_performance', 'metric_name')
    op.drop_column('model_performance', 'horizon_days')
    op.drop_column('model_performance', 'metric_value')
    op.drop_column('model_performance', 'sample_size')
    op.drop_column('model_performance', 'model_name')
    op.add_column('sec_company_facts', sa.Column('concept', sa.String(), nullable=False))
    op.add_column('sec_company_facts', sa.Column('unit', sa.String(), nullable=False))
    op.add_column('sec_company_facts', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('sec_company_facts', sa.Column('fy', sa.Integer(), nullable=True))
    op.add_column('sec_company_facts', sa.Column('fp', sa.String(), nullable=True))
    op.add_column('sec_company_facts', sa.Column('filed', sa.Date(), nullable=True))
    op.add_column('sec_company_facts', sa.Column('accn', sa.String(), nullable=True))
    op.alter_column('sec_company_facts', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_index(op.f('idx_sec_facts_date'), table_name='sec_company_facts')
    op.drop_index(op.f('idx_sec_facts_name'), table_name='sec_company_facts')
    op.create_index('idx_sec_facts_concept', 'sec_company_facts', ['concept'], unique=False)
    op.create_index('idx_sec_facts_end_date', 'sec_company_facts', ['end_date'], unique=False)
    op.drop_column('sec_company_facts', 'fact_name')
    op.drop_column('sec_company_facts', 'fact_label')
    op.drop_column('sec_company_facts', 'fiscal_period')
    op.drop_column('sec_company_facts', 'filed_date')
    op.drop_column('sec_company_facts', 'fiscal_year')
    op.drop_column('sec_company_facts', 'units')
    op.add_column('technical_features', sa.Column('macd_histogram', sa.Float(), nullable=True))
    op.add_column('technical_features', sa.Column('keltner_upper', sa.Float(), nullable=True))
    op.add_column('technical_features', sa.Column('keltner_lower', sa.Float(), nullable=True))
    op.add_column('technical_features', sa.Column('obv_sma', sa.Float(), nullable=True))
    op.add_column('technical_features', sa.Column('ad_line', sa.Float(), nullable=True))
    op.add_column('technical_features', sa.Column('cmf', sa.Float(), nullable=True))
    op.add_column('technical_features', sa.Column('vwap', sa.Float(), nullable=True))
    op.add_column('technical_features', sa.Column('price_to_sma20', sa.Float(), nullable=True))
    op.add_column('technical_features', sa.Column('price_to_sma50', sa.Float(), nullable=True))
    op.add_column('technical_features', sa.Column('price_to_sma200', sa.Float(), nullable=True))
    op.add_column('technical_features', sa.Column('volume_ratio', sa.Float(), nullable=True))
    op.create_index('idx_tech_ticker_date', 'technical_features', ['ticker', 'date'], unique=False)
    op.drop_column('technical_features', 'returns_20d')
    op.drop_column('technical_features', 'returns_1d')
    op.drop_column('technical_features', 'volatility_20d')
    op.drop_column('technical_features', 'obv_ema')
    op.drop_column('technical_features', 'macd_hist')
    op.drop_column('technical_features', 'returns_5d')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technical_features', sa.Column('returns_5d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('technical_features', sa.Column('macd_hist', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('technical_features', sa.Column('obv_ema', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('technical_features', sa.Column('volatility_20d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('technical_features', sa.Column('returns_1d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('technical_features', sa.Column('returns_20d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index('idx_tech_ticker_date', table_name='technical_features')
    op.drop_column('technical_features', 'volume_ratio')
    op.drop_column('technical_features', 'price_to_sma200')
    op.drop_column('technical_features', 'price_to_sma50')
    op.drop_column('technical_features', 'price_to_sma20')
    op.drop_column('technical_features', 'vwap')
    op.drop_column('technical_features', 'cmf')
    op.drop_column('technical_features', 'ad_line')
    op.drop_column('technical_features', 'obv_sma')
    op.drop_column('technical_features', 'keltner_lower')
    op.drop_column('technical_features', 'keltner_upper')
    op.drop_column('technical_features', 'macd_histogram')
    op.add_column('sec_company_facts', sa.Column('units', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('sec_company_facts', sa.Column('fiscal_year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sec_company_facts', sa.Column('filed_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('sec_company_facts', sa.Column('fiscal_period', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('sec_company_facts', sa.Column('fact_label', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('sec_company_facts', sa.Column('fact_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index('idx_sec_facts_end_date', table_name='sec_company_facts')
    op.drop_index('idx_sec_facts_concept', table_name='sec_company_facts')
    op.create_index(op.f('idx_sec_facts_name'), 'sec_company_facts', ['fact_name'], unique=False)
    op.create_index(op.f('idx_sec_facts_date'), 'sec_company_facts', ['end_date'], unique=False)
    op.alter_column('sec_company_facts', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('sec_company_facts', 'accn')
    op.drop_column('sec_company_facts', 'filed')
    op.drop_column('sec_company_facts', 'fp')
    op.drop_column('sec_company_facts', 'fy')
    op.drop_column('sec_company_facts', 'start_date')
    op.drop_column('sec_company_facts', 'unit')
    op.drop_column('sec_company_facts', 'concept')
    op.add_column('model_performance', sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('model_performance', sa.Column('sample_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('model_performance', sa.Column('metric_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('model_performance', sa.Column('horizon_days', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('model_performance', sa.Column('metric_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index('idx_perf_model', table_name='model_performance')
    op.create_index(op.f('idx_perf_model'), 'model_performance', ['model_name'], unique=False)
    op.drop_column('model_performance', 'evaluation_period_days')
    op.drop_column('model_performance', 'correct_predictions')
    op.drop_column('model_performance', 'total_predictions')
    op.drop_column('model_performance', 'sharpe_ratio')
    op.drop_column('model_performance', 'brier_score')
    op.drop_column('model_performance', 'log_loss')
    op.drop_column('model_performance', 'auc_roc')
    op.drop_column('model_performance', 'f1_score')
    op.drop_column('model_performance', 'recall')
    op.drop_column('model_performance', 'precision')
    op.drop_column('model_performance', 'accuracy')
    op.drop_column('model_performance', 'ticker')
    op.drop_column('model_performance', 'model_version')
    op.add_column('ml_predictions', sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('ml_predictions', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('ml_predictions', sa.Column('predicted_return', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('ml_predictions', sa.Column('feature_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('ml_predictions', sa.Column('horizon_days', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index('idx_ml_pred_ticker_date', table_name='ml_predictions')
    op.drop_index('idx_ml_pred_ticker', table_name='ml_predictions')
    op.drop_index('idx_ml_pred_target', table_name='ml_predictions')
    op.drop_index('idx_ml_pred_date', table_name='ml_predictions')
    op.create_index(op.f('idx_pred_ticker'), 'ml_predictions', ['ticker'], unique=False)
    op.create_index(op.f('idx_pred_model'), 'ml_predictions', ['model_name'], unique=False)
    op.create_index(op.f('idx_pred_date'), 'ml_predictions', ['prediction_date'], unique=False)
    op.alter_column('ml_predictions', 'predicted_direction',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('ml_predictions', 'top_features')
    op.drop_column('ml_predictions', 'confidence_score')
    op.drop_column('ml_predictions', 'ensemble_prob')
    op.drop_column('ml_predictions', 'lstm_prob')
    op.drop_column('ml_predictions', 'lightgbm_prob')
    op.drop_column('ml_predictions', 'xgboost_prob')
    op.drop_column('ml_predictions', 'predicted_probability')
    op.drop_column('ml_predictions', 'model_version')
    op.add_column('derived_features', sa.Column('vix_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('derived_features', sa.Column('regime_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('derived_features', sa.Column('term_spread_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('derived_features', sa.Column('beta_60d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('derived_features', sa.Column('regime', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('derived_features', sa.Column('vs_spy_return', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('derived_features', sa.Column('vs_sector_return', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('derived_features', 'gap_percentage')
    op.drop_column('derived_features', 'close_position_in_range')
    op.drop_column('derived_features', 'high_low_range')
    op.drop_column('derived_features', 'quarter')
    op.drop_column('derived_features', 'month')
    op.drop_column('derived_features', 'week_of_month')
    op.drop_column('derived_features', 'day_of_week')
    op.drop_column('derived_features', 'market_beta')
    op.drop_column('derived_features', 'sector_relative_strength')
    op.drop_column('derived_features', 'sp500_correlation_30d')
    op.drop_column('derived_features', 'price_zscore')
    op.drop_column('derived_features', 'volume_regime')
    op.drop_column('derived_features', 'trend_regime')
    op.drop_column('derived_features', 'volatility_regime')
    op.drop_column('derived_features', 'momentum_volatility_ratio')
    op.drop_column('derived_features', 'volume_price_divergence')
    op.drop_column('derived_features', 'rsi_macd_interaction')
    op.drop_column('data_retention_policy', 'description')
    op.drop_column('data_retention_policy', 'partition_column')
    op.drop_column('data_retention_policy', 'archive_to_parquet')
    op.add_column('data_refresh_log', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('data_refresh_log', sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('data_refresh_log', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('data_refresh_log', sa.Column('refresh_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('data_refresh_log', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index('idx_refresh_status', table_name='data_refresh_log')
    op.drop_index('idx_refresh_source', table_name='data_refresh_log')
    op.create_index(op.f('idx_refresh_source'), 'data_refresh_log', ['source'], unique=False)
    op.create_index(op.f('idx_refresh_time'), 'data_refresh_log', ['start_time'], unique=False)
    op.alter_column('data_refresh_log', 'error_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('data_refresh_log', 'refresh_end')
    op.drop_column('data_refresh_log', 'refresh_start')
    op.drop_column('data_refresh_log', 'data_source')
    op.drop_column('data_refresh_log', 'refresh_id')
    op.create_table('sec_fails_to_deliver',
    sa.Column('settlement_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('cusip', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('settlement_date', 'cusip', name=op.f('sec_fails_to_deliver_pkey'))
    )
    op.create_index(op.f('idx_ftd_symbol'), 'sec_fails_to_deliver', ['symbol'], unique=False)
    op.create_index(op.f('idx_ftd_date'), 'sec_fails_to_deliver', ['settlement_date'], unique=False)
    op.create_table('feature_importance',
    sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('training_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('feature_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('importance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('importance_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('model_name', 'training_date', 'feature_name', name=op.f('feature_importance_pkey'))
    )
    op.create_index(op.f('idx_feat_imp_model'), 'feature_importance', ['model_name'], unique=False)
    op.create_index(op.f('idx_feat_imp_date'), 'feature_importance', ['training_date'], unique=False)
    op.create_table('sec_filings',
    sa.Column('accession_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('cik', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('form_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('filing_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('report_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('accession_number', name=op.f('sec_filings_pkey'))
    )
    op.create_index(op.f('idx_sec_filings_form'), 'sec_filings', ['form_type'], unique=False)
    op.create_index(op.f('idx_sec_filings_date'), 'sec_filings', ['filing_date'], unique=False)
    op.create_index(op.f('idx_sec_filings_cik'), 'sec_filings', ['cik'], unique=False)
    op.drop_index('idx_sec_sub_period', table_name='sec_submissions')
    op.drop_index('idx_sec_sub_form', table_name='sec_submissions')
    op.drop_index('idx_sec_sub_filed', table_name='sec_submissions')
    op.drop_index('idx_sec_sub_cik', table_name='sec_submissions')
    op.drop_table('sec_submissions')
    op.drop_index('idx_sec_fs_tag', table_name='sec_financial_statements')
    op.drop_index('idx_sec_fs_ddate', table_name='sec_financial_statements')
    op.drop_index('idx_sec_fs_adsh', table_name='sec_financial_statements')
    op.drop_table('sec_financial_statements')
    op.drop_index('idx_news_ticker', table_name='news_sentiment')
    op.drop_index('idx_news_sentiment', table_name='news_sentiment')
    op.drop_index('idx_news_published', table_name='news_sentiment')
    op.drop_table('news_sentiment')
    op.drop_index('idx_registry_ticker', table_name='model_registry')
    op.drop_index('idx_registry_status', table_name='model_registry')
    op.drop_index('idx_registry_name_version', table_name='model_registry')
    op.drop_table('model_registry')
    op.drop_index('idx_ml_train_ticker', table_name='ml_training_data')
    op.drop_index('idx_ml_train_split', table_name='ml_training_data')
    op.drop_table('ml_training_data')
    op.drop_index('idx_drift_feature', table_name='feature_drift')
    op.drop_index('idx_drift_date', table_name='feature_drift')
    op.drop_table('feature_drift')
    op.drop_index('idx_api_key_hash', table_name='api_keys')
    op.drop_index('idx_api_key_active', table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
